# Generated by Django 4.0.4 on 2023-04-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_location_lat_remove_user_location_lng_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
